config/routes.rb
RR04::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :activity_events

  resources :user_activities

  resources :activities

  resources :activity_types

  resources :users
  
  get "home/index"
  
  root :to => "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
	
	#attr_accessible :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :attach

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :fname, :lname, :email, :password, :password_confirmation, :remember_me
  
  has_many :user_roles, :dependent => :destroy
  has_many :roles, :through => :user_roles

  # does this user have the specified role in its role list?
  def has_role?(role_sym)
    roles.any? { |role| role.name.underscore.to_sym == role_sym.downcase }
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  
  before_filter :get_user, :only => [:index,:new,:edit]
  before_filter :accessible_roles, :only => [:new, :edit, :show, :update, :create]
  load_and_authorize_resource :only => [:show, :new, :destroy, :edit, :update]
 
  # Get roles accessible by the current user
  #----------------------------------------------------
  def accessible_roles
    @accessible_roles = Role.accessible_by(current_ability,:read)
  end
 
  # Make the current user object available to views
  #----------------------------------------
  def get_user
    @current_user = current_user
  end
  
  # GET /users
  # GET /users.xml                                                
  # GET /users.json                                       HTML and AJAX
  #-----------------------------------------------------------------------
  def index
    @users = User.accessible_by(current_ability, :index).limit(20)
    respond_to do |format|
      format.json { render :json => @users }
      format.xml  { render :xml => @users }
      format.html
    end
  end
 
  # GET /users/new
  # GET /users/new.xml                                            
  # GET /users/new.json                                    HTML AND AJAX
  #-------------------------------------------------------------------
  def new
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
  end
 
  # GET /users/1
  # GET /users/1.xml                                                       
  # GET /users/1.json                                     HTML AND AJAX
  #-------------------------------------------------------------------
  def show
    respond_to do |format|
      format.json { render :json => @user }
      format.xml  { render :xml => @user }
      format.html      
    end
 
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
 
  # GET /users/1/edit                                                      
  # GET /users/1/edit.xml                                                      
  # GET /users/1/edit.json                                HTML AND AJAX
  #-------------------------------------------------------------------
  def edit
    respond_to do |format|
      format.json { render :json => @user }   
      format.xml  { render :xml => @user }
      format.html
    end
 
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
 
  # DELETE /users/1     
  # DELETE /users/1.xml
  # DELETE /users/1.json                                  HTML AND AJAX
  #-------------------------------------------------------------------
  def destroy
    @user.destroy!
 
    respond_to do |format|
      format.json { respond_to_destroy(:ajax) }
      format.xml  { head :ok }
      format.html { respond_to_destroy(:html) }      
    end
 
  rescue ActiveRecord::RecordNotFound
    respond_to_not_found(:json, :xml, :html)
  end
 
  # POST /users
  # POST /users.xml         
  # POST /users.json                                      HTML AND AJAX
  #-----------------------------------------------------------------
  def create     
    @user = User.create( params[:user] )
 
    if @user.save
      respond_to do |format|
        format.json { render :json => @user.to_json, :status => 200 }
        format.xml  { head :ok }
        format.html { redirect_to :action => :index }
      end
    else
      respond_to do |format|
        format.json { render :text => "Could not create user", :status => :unprocessable_entity } # placeholder
        format.xml  { head :ok }
        format.html { render :action => :new, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  #-----------------------------------------------------------------
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Generates a set of checkboxes for a HABTM assignment in a form. Labels are properly assigned
  # to the checkboxes and markup is valid HTML.
  #
  # habtm_checkboxes(@organizer, :event_ids, @events, :name)
  #
  # <%= hidden_field_tag "organizer[event_ids][]", "" %>
  # <% @events.each do |event| -%>
  # <%= check_box_tag "organizer[event_ids][]", event.id, @organizer.event_ids.include?(event.id), :id => "organizer_events_id_#{event.id}" %>
  # <%= label_tag "organizer_events_id_#{event.id}", h(event.name) %>
  # <% end -%>
  def habtm_checkboxes(obj, column, assignment_objects, assignment_object_display_column)
    obj_to_s = obj.class.to_s.split("::").last.underscore
    field_name = "#{obj_to_s}[#{column}][]"
    
    html = hidden_field_tag(field_name, "")
    assignment_objects.each do |assignment_obj|
      cbx_id = "#{obj_to_s}_#{column}_#{assignment_obj.id}"
      html += check_box_tag field_name, assignment_obj.id, obj.send(column).include?(assignment_obj.id), :id => cbx_id
      html += label_tag cbx_id, h(assignment_obj.send(assignment_object_display_column))
      html += content_tag(:br)
    end
    html
  end
end

app/views/users/_user_fields.html.erb
<p><%= f.label :fname %></p>
<p><%= f.text_field :fname %></p>
 
<p><%= f.label :lname %></p>
<p><%= f.text_field :lname %></p>
 
<% if can? :read, Role %>
  <p><%= f.label :role %></p>
  <ul class="no-pad no-bullets">
    <%= habtm_checkboxes(@user, :role_ids, @accessible_roles, :name); %>
  </ul>
<% end %>

<%= form_for @user, :url => user_path, :html => { :multipart => true } do |form| %>
  <%= form.file_field :avatar %>
<% end %>

app/views/users/edit.html.erb
<h3><%= @user == @current_user ? "Your Account Settings" : "Edit User" %></h3>
 
<%= form_for(@user, :html => { :method => :put }) do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
     <p><%= msg %></p>
  <% end %>
  
  <%= render :partial => 'user_fields', :locals => { :f => f } %>
 
  <p><%= f.label :password %> <i>(leave blank if you don't want to change it)</i></p>
  <p><%= f.password_field :password %></p>
 
  <p><%= f.label :password_confirmation %></p>
  <p><%= f.password_field :password_confirmation %></p>
 
  <p><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i></p>
  <p><%= f.password_field :current_password %></p>
 
  <p><%= f.submit "Update" %></p>
<% end %>
<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>F Name</th>
    <th>L Name</th>
    <th>Email</th>
    <th>Roles</th>
    <th>Action</th>
    <th>Action</th>
  </tr>

<% @users.each do |u| %>
  <tr>
    <td><%= link_to_if(can?(:read, User), "#{u.fname}", user_path(u.id)) {} %></td>
    <td><%= link_to_if(can?(:read, User), "#{u.lname}", user_path(u.id)) {} %></td>
    <td><%= "#{u.email}" %></td>
    <td><%= "#{u.roles.collect{|r| r.name}}" %></td>
    <td><%= link_to_if(can?(:edit, User), "Edit", edit_user_path(u.id)) {} %></td>
    <td><%= link_to_if(can?(:delete, u), "Delete", u, :confirm => "Are you sure?", :method => :delete) {} %></td>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<h3><%= @user.fname %> <%= @user.lname %></h3>
 
<%= link_to_if(can?(:update,@user), "Edit", edit_user_path(@user)) %> |
<%= link_to_if(can?(:delete, @user), "Delete", user_path(@user), :confirm => "Are you sure?", :method => :delete) {} %>
 
<table class="one-column-emphasis">
  <tbody>
    <tr>
      <td class="oce-first">Email:</td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td class="oce-first">Role:</td>
      <td><%= @user.roles.first.name %></td>
    </tr>
    
    <tr>
      <td class="oce-first">Avatar:</td>
      <td>
        <%= image_tag @user.avatar.url %>
        <%= image_tag @user.avatar.url(:medium) %>
        <%= image_tag @user.avatar.url(:thumb) %>
      </td>
    </tr>

  <% if can?(:see_timestamps,User) %>
    <tr>
      <td class="oce-first">Created at:</td>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <td class="oce-first">Last Sign In:</td>
      <td><%= @user.last_sign_in_at %></td>
    </tr>
    <tr>
      <td class="oce-first">Sign In Count:</td>
      <td><%= @user.sign_in_count %></td>
    </tr>
  <% end %>
  </tbody>
</table>