config/routes.rb
RR04::Application.routes.draw do
  
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :activity_events

  resources :user_activities

  resources :activities

  resources :activity_types

  resources :users
  
  get "home/index"
  
  root :to => "home#index"
end

app/models/activity_event.rb
class ActivityEvent < ActiveRecord::Base
  belongs_to :userActivity

  #attr_accessible :amount, :journalEntry
end

app/controllers/activity_events_controller.rb
class ActivityEventsController < ApplicationController
  # GET /activity_events
  # GET /activity_events.json
  def index
    @activity_events = ActivityEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activity_events }
    end
  end

  # GET /activity_events/1
  # GET /activity_events/1.json
  def show
    @activity_event = ActivityEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity_event }
    end
  end

  # GET /activity_events/new
  # GET /activity_events/new.json
  def new
    @activity_event = ActivityEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity_event }
    end
  end

  # GET /activity_events/1/edit
  def edit
    @activity_event = ActivityEvent.find(params[:id])
  end

  # POST /activity_events
  # POST /activity_events.json
  def create
    @activity_event = ActivityEvent.new(params[:activity_event])

    respond_to do |format|
      if @activity_event.save
        format.html { redirect_to @activity_event, notice: 'Activity event was successfully created.' }
        format.json { render json: @activity_event, status: :created, location: @activity_event }
      else
        format.html { render action: "new" }
        format.json { render json: @activity_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activity_events/1
  # PUT /activity_events/1.json
  def update
    @activity_event = ActivityEvent.find(params[:id])

    respond_to do |format|
      if @activity_event.update_attributes(params[:activity_event])
        format.html { redirect_to @activity_event, notice: 'Activity event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_events/1
  # DELETE /activity_events/1.json
  def destroy
    @activity_event = ActivityEvent.find(params[:id])
    @activity_event.destroy

    respond_to do |format|
      format.html { redirect_to activity_events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activity_events_helper.rb
module ActivityEventsHelper
end

app/views/activity_events/_form.html.erb
<%= form_for(@activity_event) do |f| %>
  <% if @activity_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_event.errors.count, "error") %> prohibited this activity_event from being saved:</h2>

      <ul>
      <% @activity_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userActivity %><br />
    <%= f.text_field :userActivity %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :journalEntry %><br />
    <%= f.text_field :journalEntry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activity_events/edit.html.erb
<h1>Editing activity_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity_event %> |
<%= link_to 'Back', activity_events_path %>

app/views/activity_events/index.html.erb
<h1>Listing activity_events</h1>

<table>
  <tr>
    <th>Useractivity</th>
    <th>Amount</th>
    <th>Journalentry</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activity_events.each do |activity_event| %>
  <tr>
    <td><%= activity_event.userActivity %></td>
    <td><%= activity_event.amount %></td>
    <td><%= activity_event.journalEntry %></td>
    <td><%= link_to 'Show', activity_event %></td>
    <td><%= link_to 'Edit', edit_activity_event_path(activity_event) %></td>
    <td><%= link_to 'Destroy', activity_event, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity event', new_activity_event_path %>

app/views/activity_events/new.html.erb
<h1>New activity_event</h1>

<%= render 'form' %>

<%= link_to 'Back', activity_events_path %>

app/views/activity_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Useractivity:</b>
  <%= @activity_event.userActivity %>
</p>

<p>
  <b>Amount:</b>
  <%= @activity_event.amount %>
</p>

<p>
  <b>Journalentry:</b>
  <%= @activity_event.journalEntry %>
</p>


<%= link_to 'Edit', edit_activity_event_path(@activity_event) %> |
<%= link_to 'Back', activity_events_path %>